# Generated by Django 5.2.7 on 2025-10-30 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True, help_text="Desmarcar para 'dar de baja' esta causa sin borrarla")),
            ],
            options={
                'verbose_name': 'Causa Probable',
                'verbose_name_plural': 'Causas Probables',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True, help_text="Desmarcar para 'dar de baja' este tipo sin borrarlo")),
            ],
            options={
                'verbose_name': 'Tipo de Siniestro',
                'verbose_name_plural': 'Tipos de Siniestros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, help_text='Fecha y hora del siniestro')),
                ('latitud', models.FloatField(help_text='Latitud del siniestro')),
                ('longitud', models.FloatField(help_text='Longitud del siniestro')),
                ('via', models.CharField(blank=True, help_text='Tipo de vía donde ocurrió el siniestro', max_length=200)),
                ('grado_severidad', models.CharField(choices=[('CON_FALLECIDOS', 'con fallecidos en sitio'), ('CON_LESIONADOS', 'con lesionados'), ('SOLO_DANOS', 'solo con danos materiales')], max_length=20)),
                ('causa_probable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='siniestros.causa')),
                ('tipo_siniestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='siniestros.tiposiniestro')),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad de la víctima', null=True)),
                ('condicion', models.CharField(choices=[('FALLECIDO', 'Fallecido'), ('LESIONADO', 'Lesionado'), ('ILESO', 'Ileso')], db_index=True, max_length=20)),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('NO_REGISTRA', 'No registra')], default='NO_REGISTRA', max_length=20)),
                ('actor_vial', models.CharField(choices=[('PEATON', 'Peatón'), ('MOTOCICLETA', 'Ocupante Motocicleta'), ('VEH_LIVIANO', 'Ocupante Veh. Liviano'), ('CICLISTA', 'Ciclista'), ('SCOOTER', 'Ocupante Scooter'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victimas', to='siniestros.siniestro')),
            ],
        ),
    ]
