# Generated by Django 5.2.7 on 2025-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AlterModelOptions(
            name='victima',
            options={'ordering': ['-siniestro__fecha_hora']},
        ),
        migrations.AlterField(
            model_name='causa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='latitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='longitud',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='via',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tiposiniestro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='victima',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='siniestro',
            index=models.Index(fields=['-fecha_hora'], name='siniestros__fecha_h_37ba76_idx'),
        ),
        migrations.AddIndex(
            model_name='siniestro',
            index=models.Index(fields=['grado_severidad'], name='siniestros__grado_s_8fb309_idx'),
        ),
        migrations.AddIndex(
            model_name='victima',
            index=models.Index(fields=['condicion'], name='siniestros__condici_d21f59_idx'),
        ),
        migrations.AddIndex(
            model_name='victima',
            index=models.Index(fields=['sexo'], name='siniestros__sexo_cede0a_idx'),
        ),
    ]
