# Generated by Django 5.2.7 on 2025-11-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0002_alter_siniestro_options_alter_victima_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='victima',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='siniestro',
            name='siniestros__fecha_h_37ba76_idx',
        ),
        migrations.RemoveIndex(
            model_name='siniestro',
            name='siniestros__grado_s_8fb309_idx',
        ),
        migrations.RemoveIndex(
            model_name='victima',
            name='siniestros__condici_d21f59_idx',
        ),
        migrations.RemoveIndex(
            model_name='victima',
            name='siniestros__sexo_cede0a_idx',
        ),
        migrations.AlterField(
            model_name='causa',
            name='activo',
            field=models.BooleanField(default=True, help_text="Desmarcar para 'dar de baja' esta causa sin borrarla"),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora del siniestro'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='latitud',
            field=models.FloatField(help_text='Latitud del siniestro'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='longitud',
            field=models.FloatField(help_text='Longitud del siniestro'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='via',
            field=models.CharField(blank=True, help_text='Tipo de vía donde ocurrió el siniestro', max_length=200),
        ),
        migrations.AlterField(
            model_name='tiposiniestro',
            name='activo',
            field=models.BooleanField(default=True, help_text="Desmarcar para 'dar de baja' este tipo sin borrarlo"),
        ),
        migrations.AlterField(
            model_name='victima',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad de la víctima', null=True),
        ),
    ]
