# Generated by Django 5.2.7 on 2025-12-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0003_alter_siniestro_options_alter_victima_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='grado_severidad',
            field=models.CharField(choices=[('CON_FALLECIDOS', 'Con fallecidos en sitio'), ('CON_LESIONADOS', 'Con lesionados'), ('SOLO_DANOS', 'Solo con daños materiales')], max_length=20),
        ),
    ]
