# Generated by Django 5.2.7 on 2026-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0004_alter_siniestro_grado_severidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Siniestro', 'verbose_name_plural': 'Siniestros'},
        ),
        migrations.AddField(
            model_name='siniestro',
            name='barrio',
            field=models.CharField(blank=True, db_index=True, help_text='Barrio donde ocurrió', max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='calle_principal',
            field=models.CharField(blank=True, help_text='Calle o avenida principal', max_length=200),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='calle_secundaria',
            field=models.CharField(blank=True, help_text='Calle o avenida secundaria', max_length=200),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='condicion_atmosferica',
            field=models.CharField(blank=True, help_text='Condición climática', max_length=50),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='condicion_calzada',
            field=models.CharField(blank=True, db_index=True, help_text='Estado de la calzada', max_length=50),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='condicion_via',
            field=models.CharField(blank=True, help_text='Estado de la vía', max_length=50),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales del CSV original (vehículos, conductores, placas, etc.)'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='descripcion_dano_bien_publico',
            field=models.TextField(blank=True, help_text='Descripción del daño al bien público'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='direccion_completa',
            field=models.TextField(blank=True, help_text='Dirección registrada completa'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='lugar_en_via',
            field=models.CharField(blank=True, help_text='Lugar específico en la vía', max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='luz_artificial',
            field=models.CharField(blank=True, help_text='Presencia de luz artificial', max_length=50),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='num_fallecidos',
            field=models.IntegerField(default=0, help_text='Número de personas fallecidas'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='num_heridos',
            field=models.IntegerField(default=0, help_text='Número de personas heridas'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='num_personas_detenidas',
            field=models.IntegerField(default=0, help_text='Número de personas detenidas'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='num_pruebas_alcohotest',
            field=models.IntegerField(default=0, help_text='Número de pruebas de alcohotest realizadas'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='num_vehiculos_involucrados',
            field=models.IntegerField(db_index=True, default=0, help_text='Número de vehículos involucrados'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='parroquia',
            field=models.CharField(blank=True, db_index=True, help_text='Parroquia urbana', max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='parroquia_rural',
            field=models.CharField(blank=True, help_text='Parroquia rural', max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='referencia',
            field=models.TextField(blank=True, help_text='Referencia del lugar'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='senalizacion_existente',
            field=models.CharField(blank=True, help_text='Señalización existente', max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tiene_danos_bien_publico',
            field=models.BooleanField(default=False, help_text='¿Hubo daños al bien público?'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tipos_vehiculos',
            field=models.TextField(blank=True, help_text='Tipos de vehículos separados por coma'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculos_comercial',
            field=models.IntegerField(default=0, help_text='Cantidad de vehículos comerciales'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculos_particular',
            field=models.IntegerField(default=0, help_text='Cantidad de vehículos particulares'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculos_publico',
            field=models.IntegerField(default=0, help_text='Cantidad de vehículos públicos'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='vehiculos_retenidos',
            field=models.IntegerField(default=0, help_text='Número de vehículos retenidos'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='zona',
            field=models.CharField(blank=True, help_text='Zona urbana/rural', max_length=100),
        ),
    ]
