# Generated by Django 6.0 on 2026-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0005_alter_siniestro_options_siniestro_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales del CSV original'),
        ),
    ]
