# Generated by Django 5.2.7 on 2025-11-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la línea (ej. L10)', max_length=100, unique=True)),
                ('color', models.CharField(help_text='Color en formato hexadecimal (ej. #FF0000)', max_length=7)),
                ('coordenadas', models.JSONField(blank=True, default=list, help_text='Array de coordenadas [[lat, lng], [lat, lng], ...]')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Línea de Bus',
                'verbose_name_plural': 'Líneas de Bus',
                'ordering': ['nombre'],
            },
        ),
    ]
