# Generated by Django 5.2.7 on 2025-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabus',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles o información adicional sobre la ruta.', null=True),
        ),
        migrations.AddField(
            model_name='lineabus',
            name='destino',
            field=models.CharField(default='', help_text='Punto final o terminal de la línea.', max_length=100),
        ),
        migrations.AddField(
            model_name='lineabus',
            name='origen',
            field=models.CharField(default='', help_text='Punto de inicio o terminal de la línea.', max_length=100),
        ),
        migrations.AddField(
            model_name='lineabus',
            name='tarifa_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa base del pasaje.', max_digits=6),
        ),
    ]
