# Generated by Django 5.2.7 on 2025-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_lineabus_descripcion_lineabus_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineabus',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='lineabus',
            name='geom',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de geometría GeoJSON de la ruta de la línea de bus (LineString).'),
        ),
    ]
