# Generated by Django 5.2.7 on 2025-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_remove_lineabus_coordenadas_lineabus_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclovia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la ciclovía o segmento', max_length=100, unique=True)),
                ('geom', models.JSONField(blank=True, default=dict, help_text='Geometría GeoJSON LineString de la ciclovía. Formato [lng, lat]')),
                ('longitud_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Longitud total en kilómetros', max_digits=5)),
                ('tipo_separacion', models.CharField(choices=[('Pintada', 'Ciclovía Pintada'), ('Confinada', 'Ciclovía Confinada'), ('Mixta', 'Ciclovía Mixta')], default='Pintada', help_text="Tipo de separación: 'Pintada', 'Confinada', 'Mixta'", max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciclovía',
                'verbose_name_plural': 'Ciclovías',
                'ordering': ['nombre'],
            },
        ),
    ]
