# Generated by Django 5.2.7 on 2025-12-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_ciclovia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclovia',
            name='color',
            field=models.CharField(default='#008000', help_text='Color en formato hexadecimal (ej. #008000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='ciclovia',
            name='geom',
            field=models.JSONField(blank=True, default=dict, help_text='Geometría GeoJSON LineString de la ruta. Formato [lng, lat]'),
        ),
    ]
