# Generated by Django 5.2.7 on 2026-01-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_ciclovia_color_alter_ciclovia_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclovia',
            name='geom',
            field=models.JSONField(blank=True, default=dict, help_text='Geometria GeoJSON LineString de la ruta. Formato [lng, lat]', null=True),
        ),
        migrations.AlterField(
            model_name='lineabus',
            name='geom',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de geometria GeoJSON de la ruta de la linea de bus (LineString).', null=True),
        ),
    ]
