# Generated by Django 5.2.7 on 2026-01-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_allow_null_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabus',
            name='paradas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de paradas en formato [[lng, lat, 'nombre opcional'], ...]", null=True),
        ),
        migrations.AddField(
            model_name='lineabus',
            name='tarifa_preferencial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa preferencial/reducida (tercera edad, discapacidad, etc.).', max_digits=6),
        ),
    ]
