# Generated by Django 5.2.7 on 2026-01-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0007_lineabus_paradas_lineabus_tarifa_preferencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabus',
            name='horario_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin del servicio (ej. 22:30:00)', null=True),
        ),
        migrations.AddField(
            model_name='lineabus',
            name='horario_inicio',
            field=models.TimeField(blank=True, help_text='Hora de inicio del servicio (ej. 06:00:00)', null=True),
        ),
        migrations.AddField(
            model_name='lineabus',
            name='intervalo_minutos',
            field=models.IntegerField(default=0, help_text='Frecuencia/Intervalo de paso en minutos'),
        ),
    ]
